export const CALCULATE_TOTAL = "CALCULATE_TOTAL";
export const OPEN_FORM_RENTAL = "OPEN_FORM_RENTAL";
export const SET_PARAMETERS = "SET_PARAMETERS";
export const RESET_TOTAL = "RESET_TOTAL"
export const GET_RENTAL_PARAMETERS = "GET_RENTAL_PARAMETERS";